version: '3.7'

services:
  database_projetonode:
    image: postgres
    container_name: database_projetonode
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=node
      - POSTGRES_DB=projetonode
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: projetonode
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_projetonode
    depends_on:
      - database_projetonode
    restart: always

volumes:
  pgdata:
    driver: local
